### ISSUE TITLE
Allow sorting of the leaderboard by time as well as # of attempts

### ISSUE THREAD

**Issue by PeteRimkus** [hryanjones/guess-my-word#14]
Please allow sorting of the leaderboard by time as well as # of attempts

**Comment by hryanjones** [comment]
Thanks for the creature request!

I do plan to do this, but I have a bit of a rewrite of the frontend that should happen first as it'll unblock a number of features. (Vanilla JS was good for the first version, but becoming a bit of a mess now).

**Comment by PeteRimkus** [comment]
Thanks!

**Comment by hryanjones** [comment]
@amygoldstein

Now that I have the leaderboard separated it wasn't too hard to add this in. Closing this issue https://github.com/hryanjones/guess-my-word/commit/6f2aae81731a15b65a53bcddd8654e9b03b7e5c3

If you find any bugs please let me know.
