### ISSUE TITLE
Please add ability to see other people's guesses

### ISSUE THREAD

**Issue by mjbrailsford** [hryanjones/guess-my-word#16]
Can you add the ability to see what words people guessed?

**Comment by hryanjones** [comment]
I'll likely get to this fairly soon, but the survey showed that people are most interested in:
1. playing words for previous days, and
2. having a leaderboard "for all time"

So, I'll work on these first and then this one will be next.

**Comment by mjbrailsford** [comment]
Thank you!

I really appreciate you bringing this back!

**Comment by hryanjones** [comment]
(oh, this has been done, closing)
