### ISSUE TITLE
Please consider adding a filter on username. There is an inappropriate user name on the board.  

### ISSUE THREAD

**Issue by Chaeng** [hryanjones/guess-my-word#18]

**Comment by hryanjones** [comment]
Which one? Also, this sounds like a difficult business to get in. How would you feel about something like this:
1. put a button next to all usernames that says "report inappropriate"
2. If 2 or more people click this for a user there name will be hidden, but user's can click to view it if they want
3. If the same username is marked as inappropriate on more than one day it'd *always* show up as hidden by default

Would something like that work?

**Comment by Chaeng** [comment]
Hi Ryan,

I am not sure if you are logging all previous usernames. If you are, there
should be one named '_ u c _ Eric' in there (the missing word starting with
the letter F, I think you can guess what it is).  It is a difficult
business; we can't totally prevent people from using all kinds of vulgarity
on the internet.

Your idea sounds good to me. Hide those names, and label them that the
username may contain prohibited keywords or something like that.

**Comment by hryanjones** [comment]
In the shorter term I put in a simple filter for some basic bad words. If someone uses these they'll show up on the board, but their name will be "THAT GUY 🤦‍♀️".

I'm gonna keep this open to track the better long-term solution.

**Comment by Chaeng** [comment]
Ha! I like that sense of humor!
You made me want to come up with some negative test cases now ;)

**Comment by hryanjones** [comment]
I just released a hopefully long-term version which allows people to report offensive names. See this for details:

https://twitter.com/guessmyword1/status/1225297474975195138
