### ISSUE TITLE
Consider filtering user names on the scoreboard which contain the answer (for either daily puzzle)

### ISSUE THREAD

**Issue by wsulcs** [hryanjones/guess-my-word#19]
The top score on today's Normal scoreboard is "THE ANSWER TO THE HARD IS _________", which spoiled the Hard word for me.  Might be nice to hide scores which contain either the Normal or Hard word for the day.

**Comment by hryanjones** [comment]
Yeah, that's a good idea and won't be difficult, except that jerks may get creative and put spaces between them and such. I think the best thing will be to implement the idea I have for people to report bad usernames:

https://github.com/hryanjones/guess-my-word/issues/18

**Comment by hryanjones** [comment]
I put in a basic filter for the words for the day and some bad words, I'll keep the other issue open to track the better long term solution for user self-reporting inappropriate names.
