### ISSUE TITLE
Inappropriate Language

### ISSUE THREAD

**Issue by beauTifulife243** [hryanjones/guess-my-word#22]
My students and I LOVE your "Guess My Word" game!  They are motivated to return to it each day (while practicing their alphabetical skills) to see how fast they can guess the word.  However, there was a VERY inappropriate name on the board, and even though you warn the users- is there some way to ensure that this doesn't happen?  My district will disallow use if this continues.  Thank you in advance for your help.

**Comment by hryanjones** [comment]
I'm glad your students like the game and I'm very sorry that you've run into those appropriate usernames. I'm also pretty disappointed in these users ruining things for everyone and I've put in a basic filter for inappropriate language, but it can't catch everything.

I'm soon to start working on a version that scales better as it'll allow users to report specific names to hide and I've got another issue tracking that, so I'll close this one in favor of that:
https://github.com/hryanjones/guess-my-word/issues/18#issuecomment-559270422

**Comment by hryanjones** [comment]
BTWay, I just released this: https://twitter.com/guessmyword1/status/1225297474975195138
