### ISSUE TITLE
Build a backend to support a leaderboard

### ISSUE THREAD

**Issue by hryanjones** [hryanjones/guess-my-word#3]
This was a pretty fun part of the old game.

**Comment by amygoldstein** [comment]
Yes, please, if you can. That really did seem like a key part of the old game. Thanks for reviving this!

**Comment by hryanjones** [comment]
This is the piece I'm working on now. It's a fair amount of work though so may be a little while yet before I can get it ready for prime time.

**Comment by hryanjones** [comment]
I'm almost done with this and have a beta version up (I'll move this to the normal URL when I'm satisfied there's not any major bugs):

https://hryanjones.com/guess-my-word/beta.html

**Comment by amygoldstein** [comment]
Great, and a few questions/comments.

You’ve got separate boards for normal and hard words, but that’s not all that clear—maybe make the big heads “Normal Words Leaderboard” and “Hard Words Leaderboard” or some such.

Are these just the leaderboards for the day’s word? Will there also be cumulative boards?

I can’t tell from my single sample how a board will look with multiple players, but I’m guessing it’ll be arranged by least number of guesses, within which will be by quickest times. It would be great if you could toggle (like Joon’s did) between speed and guesses boards. I, for example, play more for speed, so I want to see how I did on that the most.

If you have cumulative boards, it would be great if they could indicate how many times you've played, as Joon’s did. Eventually that gets interesting.

Maybe be in touch with Joon for tips on all this?

Thanks again for doing this!

**Comment by hryanjones** [comment]
Thanks Amy. I'll definitely make the update to the title for which leaderboard it is and the second sorting based on time (as both of those are pretty easy) as the first sorting is based on number of guesses.

I've had similar thoughts on free sorting and such, but the frontend needs a bit of a rewrite to make that work well and not have spaghetti code, so it may be a little ways down the line.

I don't remember the cumulative boards from the original, but I could add a unique identifier for a user so that they could track their data over time (and still be allowed to put a different name if they want, or do you think that it should auto-fill the name they used previously?).

Lastly, do you know Joon? I've tried to get in touch with them in the past (via their GMW blog) and not succeeded.

**Comment by amygoldstein** [comment]
In the original, I think you had to enter your name every day, which worked fine. So you chose whether to disguise your crappy scores.

I do know Joon, and can give you his email address. Please write me from your regular email so this isn’t public, and I’ll send it to you. I’m sure he’d be delighted to hear from you.

**Comment by hryanjones** [comment]
Nice! I don't see a way to get your email and mine is out there already so here ya go: hryanjones@gmail.com

**Comment by hryanjones** [comment]
Thanks for continuing to test the beta :). Unless I discover a big bug I'm planning to release it tomorrow night.

**Comment by hryanjones** [comment]
Alright, I released it to the main game. Thanks again for all your input :)
