### ISSUE TITLE
Add total number of guessers to completion boards

### ISSUE THREAD

**Issue by MargoMargo** [hryanjones/guess-my-word#30]
When I go to the completion board, I would like to see how many people played so far today. I'm thinking just a simple total.

**Comment by hryanjones** [comment]
I've been meaning to do that for a while and it's not hard. I added it to the name header on the board.

Thanks for the suggestion!

https://github.com/hryanjones/guess-my-word/commit/5a8cdf443fd921d6eb99e421b9cdfe460196097e
