### ISSUE TITLE
No submit button

### ISSUE THREAD

**Issue by jlscott76** [hryanjones/guess-my-word#31]
Just completed the hard word and there is no button to submit so my result has not gone onto the leader board. Have tried refreshing page and restarting browser. Has happened on occasion previously too.

**Comment by hryanjones** [comment]
I haven't heard of this issue before. Can I get a screenshot?

Also, if you're on a computer (not a phone) can you open the developer tools for your browser and include this in the screenshot? (if you're on Windows pushing the F12 key should open it)

**Comment by jlscott76** [comment]
Thanks - screenshot attached.

Was using Samsung Internet as the browser on my Galaxy to play, when I tried using Chrome it was fine this time so will stick to Chrome in the future.

Cheers,

Jess

-------- Original Message --------

**Comment by hryanjones** [comment]
Hey Jess, I don't think GitHub picked up the image attachment. Can you go to the issue on GitHub and upload there?

**Comment by jlscott76** [comment]
![Screenshot_20200414-172720_Samsung Internet](https://user-images.githubusercontent.com/63649522/79288102-6766c900-7ef8-11ea-96e9-88ac253c2f5c.jpg)

**Comment by hryanjones** [comment]
Is the name you usually use "Messy Jessy"? I see a submit with what looks like the same guesses as in your picture.

https://hryanjones.com/guess-my-word/board.html?difficulty=hard&search=Messy%20Jessy

The only discrepancy I can see is that the time in your screenshot doesn't match the time on the board...

![messy-jessy](https://user-images.githubusercontent.com/2705396/79297419-ecb79280-7e92-11ea-93b8-997e60433818.png)

**Comment by jlscott76** [comment]
Yeah, I replayed using the Chrome browser so I could submit and just copied my guesses from the screenshot (which is why the time was so much shorter!) And then forgot that my username doesn't usually have a space in the middle. My sister and I both play and I had finally done it in less guesses than her so really wanted it to go on the board :) As I said I am having no problem in Chrome so it feels like it is a Samsung Internet browser issue.

-------- Original Message --------

**Comment by jlscott76** [comment]
![Screenshot_20200419-121546_Chrome](https://user-images.githubusercontent.com/63649522/79679338-c483b700-8237-11ea-9068-f7f1d2ccf832.jpg)

**Comment by jlscott76** [comment]
Just had the same thing occur on Chrome. Reached correct word on hard level, no submit button appeared. Is not on leader board.
