### ISSUE TITLE
Allow random play?

### ISSUE THREAD

**Issue by FranticErnie** [hryanjones/guess-my-word#33]
I just discovered this game and I'm hooked. Playing once a day is restricting, and scrolling back to previous dates is a bit chancy without keeping close track of which dates I've accessed. 

I'd like to suggest the ability to just pick a random entry (hard or normal). I personally don't care about the leaderboard, competition etc but for those who do, maybe the random choice could be a random past date? Thanks for listening

**Comment by hryanjones** [comment]
Yeah, that wouldn't be too hard.

As it's not the primary use-case of the game what would you think about the below flow:
1. when you click the calendar, there's also a "random" button in addition to calendar navigation
2. after you succeed at a random word, there's a link that suggests "play another random word"?

**Comment by FranticErnie** [comment]
That sounds just right. I does assume I'll succeed, though (-:

**Comment by hryanjones** [comment]
Sorry, wasn't hard, but took me a while to get time to do it. I didn't add the link in the success because it's easy enough to just go push random again.

https://github.com/hryanjones/guess-my-word/commit/b7f0c7078166a1f8a8aaeb64045877f09dac4948

**Comment by FranticErnie** [comment]
Fantastic. I'm pretty sure I'll use them all up in a month, but even so 
my memory's not that good. (-:

--
