### ISSUE TITLE
How about NOT sending us to another OUTSIDE SITE we want to know the daily word???

### ISSUE THREAD

**Issue by Bratface2** [hryanjones/guess-my-word#34]
I love the 'guess my word' game BUT today when I hit the 'I give up' button it sent me to an outside website! Not cool!

**Comment by hryanjones** [comment]
Yeah, it looks like that's a bug that I'll fix this weekend. Thanks for
reporting this!

Also the external website it sends you to is Duck duck go, which is
basically a privacy safe Google.

Best,
Ryan

**Comment by Bratface2** [comment]
Ryan, Thanks for getting back to me. It was odd & it was the first
time that happened.

On 6/26/2020 at 6:17 PM, "H. Ryan Jones"  wrote:

	 Yeah, it looks like that's a bug that I'll fix this weekend. Thanks
for
 reporting this!
 Also the external website it sends you to is Duck duck go, which is
 basically a privacy safe Google.
 Best,
 Ryan
 On Fri, Jun 26, 2020 at 3:55 PM Bratface2  wrote:
 > I love the 'guess my word' game BUT today when I hit the 'I give
up'
 > button it sent me to an outside website! Not cool!
 >
 > —
 > You are receiving this because you are subscribed to this thread.
 > Reply to this email directly, view it on GitHub
 > https://github.com/hryanjones/guess-my-word/issues/34>;, or
unsubscribe

**Comment by hryanjones** [comment]
Okay, should be fixed now! Sorry about that (my web framework is doing something pretty weird 🤷

https://github.com/hryanjones/guess-my-word/commit/b372381e4ca5cf511353f2873b69b576b800f0cf

**Comment by hryanjones** [comment]
Yeah, it happened because I recently added in a link to look up the word's
definition, however, there seems to be a bug in the JS framework that I use
that was causing this link to get clicked on accident afterwards. I
reported the bug to the framework makers, but in the meantime I did find a
way to prevent it from opening the link on "give up".

Cheers,
Ryan
