### ISSUE TITLE
I cannot see my words guessed on the completion board

### ISSUE THREAD

**Issue by itsmything** [hryanjones/guess-my-word#38]

**Comment by hryanjones** [comment]
What was your username and first guessed word (and was this the hard word or easy word)? Was there any weirdness when you submitted (slow or anything)?

**Comment by itsmything** [comment]
Sept 3: Username/ Try to beat my score F / Normal / Mask/ no weirdness

PS: love this game

**Comment by hryanjones** [comment]
Huh, I don't see anything out of ordinary. [The data](https://ec2.hryanjones.com/leaderboard/2020-09-03/wordlist/normal?name=Try%20to%20beat%20my%20score%20F&key=mask) looks like it's coming back correctly, specifically with your record:

`{"submitTime":"2020-09-03T11:09:51.108Z","time":141464,"numberOfGuesses":11,"name":"Try to beat my score F"}`

As you can see, your guessed words don't come back.

I was able to reproduce this by just unselecting "allow my guesses to be public" checkbox when submitting my name, which it looks like you also did. 

I think in this case you expect to be able to see your own guesses even though others can't, correct? That shouldn't be too hard to do, but it may take me a little while to get to it.

**Comment by itsmything** [comment]
Oh duh! On me
I must have unselected by mistake one day, never noticing it was there. All good
No, I have no problem making my guesses public
Sorry for the trouble
Linda

**Comment by hryanjones** [comment]
no worries, glad we figured it out and it's not a bug 😆
