### ISSUE TITLE
Please pick a license

### ISSUE THREAD

**Issue by Pascal666** [hryanjones/guess-my-word#40]
Thank you for making this code public.  Please pick a license so we know in what ways we are allowed to use this code.  Thank you!

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by hryanjones** [comment]
Will do! Should be MIT, use however you like.

If I forget and don't do this soon please let me know. (got a number of
things going on in life right now)

**Comment by hryanjones** [comment]
Okay, finally got around to doing this, sorry for delay

https://github.com/hryanjones/guess-my-word/commit/a926225f7d84d4c4ba105dc369b2f901d4246b0b
