### ISSUE TITLE
Can't see words on completion boards

### ISSUE THREAD

**Issue by soozoom** [hryanjones/guess-my-word#55]
I used to be able to see my words and other people's words on the completion boards. Now I can't. The Guesses column is empty.

**Comment by hryanjones** [comment]
Did you perhaps accidentally uncheck making your guesses public? Currently only folks who make their guesses public can see others' guesses.

**Comment by soozoom** [comment]
Hi Ryan,
Thanks for getting back to me so quickly. I may have accidentally unchecked it, but I see no way of changing it now. It no longer gives me that checkbox. Any suggestions?

Cheers,Susan

    On Wednesday, September 22, 2021, 08:41:09 PM EDT, H. Ryan Jones ***@***.***> wrote:  
 
 


Did you perhaps accidentally uncheck making your guesses public? Currently only folks who make their guesses public can see others' guesses.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hryanjones** [comment]
Next time you submit on that computer look for the checkbox right below where you enter your name for the board. It'll save the setting in your browser for future submits.

**Comment by soozoom** [comment]
Thanks, it worked!
