### ISSUE TITLE
Completion board no longer shows players’ guesses

### ISSUE THREAD

**Issue by SteinyAge** [hryanjones/guess-my-word#62]

**Comment by hryanjones** [comment]
Usually this happens when you uncheck "allow my guesses to be public", as folks who don't share their guesses currently can't see others' either. Next time you play, can you check if that's checked before submitting your name? (If it's not you need to re-check it)

**Comment by SteinyAge** [comment]
It’s definitely checked—I checked 😁

I’ve accidentally unchecked it a couple times in the past but, when I did, I could still see other people’s answers. Now, I don’t see anyone’s.

**Comment by hryanjones** [comment]
I wasn't able to reproduce this, so a few questions:
- what name do you play by?
- when was a date you played and couldn't see folks guesses?
- what browser are you using?
- what operating system? (e.g. mac, windows, android, etc.)

**Comment by SteinyAge** [comment]
Your response got me thinking so I changed my username and the problem went away!
