### ISSUE TITLE
Create a Tutorial Video for the About page

### ISSUE THREAD

**Issue by hryanjones** [hryanjones/guess-my-word#7]

**Comment by amygoldstein** [comment]
You don't need a video, but some info and instructions on the game page would be good.

**Comment by hryanjones** [comment]
Thanks Amy.

I've gotten some mixed feedback on this one. Some people like the minimal design and the input placeholder and labels were enough, but I can see adding a little more. What do you think if I added the below?

> I'm thinking of an English word. Make guesses below and I'll tell you if my word is alphabetically before or after your guess.

**Comment by amygoldstein** [comment]
I think that’s good—thanks for asking. For what it’s worth, you might want to avoid plural answers like today’s FRIENDS and verb forms with common endings like -S, -ED, and -ING. Puzzle folk are generally annoyed by stuff like that.

Really hope you can get a leaderboard going. That would be fantastic.

Thanks,
Amy

**Comment by hryanjones** [comment]
That's good feedback, I just went and removed a couple extraneous endings.

**Comment by hryanjones** [comment]
Added instruction pre-amble:

https://github.com/hryanjones/guess-my-word/commit/1546f6d3aa5ea714d1b753b57bf05e03d9d3b036

**Comment by amygoldstein** [comment]
Addendum to my earlier note: This applies to verb endings too. So today’s easy word would’ve been better without the past-tense -D ending. Thanks!

**Comment by hryanjones** [comment]
Sorry, I missed that one. I took another look through the future normal words and made some modifications to reduce these again.
