### ISSUE TITLE
GMW option to revert back to light background!

### ISSUE THREAD

**Issue by Bratface23** [hryanjones/guess-my-word#71]
The new dark background on GMW is weird & distracting! I only use a dark background on sites where I'm on for more than 5 minutes! You have taken all the enjoyment out of playing the game!!! Please change it back or at least give us the option of which background WE WANT!

**Comment by hryanjones** [comment]
Sorry for the delay, the contributor gave me a start and I fixed it up so there's a toggle and it persists.

**Comment by Bratface23** [comment]
Thanks Ryan, BUT my name did not appear on the completion board? I did finally find it but it is hidden in one of the black bands! Not sure why they are there (a leftover from the change back?).

**Comment by Bratface23** [comment]
Thanks Ryan, BUT my name did not appear on the completion board? I did
finally find but it is hidden in one of the black bands! Not sure why they
are there (a leftover from the change back?).

**Comment by hryanjones** [comment]
I undid all the dark mode changes, sorry that I accepted a half baked
change.
__________________________________________
hryanjones.com
